### ISSUE TITLE
Add Docker Support

### ISSUE THREAD

**Issue by jaiakash** [FurqanAnwar/Icovia-Clone#1]
Adding docker support by generating Dockerfile will very much shorten the menace for a developer/admin to host the project in their own system/cloud. Additionally Dockerfile will also support a standardized development environment virtualized to test and experiment with the project.

**Comment by jaiakash** [comment]
@FurqanAnwar Can i help with dockerising the project. Please assign the issue with me.

**Comment by FurqanAnwar** [comment]
@jaiakash  yeah sure go ahead

**Comment by jaiakash** [comment]
I made the PR. Can you also add the hacktober tag too.
