### ISSUE TITLE
App needs to have routing using React Router

### ISSUE THREAD

**Issue by FurqanAnwar** [FurqanAnwar/Icovia-Clone#3]
### Currently , this react app is missing routing we have 2 pages and both are on the same screen while the second page should only be visible when user click the following buttons i.e. `(Button 1 & Button 2)` as shown in pic below

![Icovia-Page-1-Updated](https://user-images.githubusercontent.com/37766405/136141133-fa68e2cd-99d8-4829-aed8-ae0bd78d7958.png)
 
### Here is what page 2 looks like

![Icovia-Page-2-Updated](https://user-images.githubusercontent.com/37766405/136141493-433ce4dc-ac92-412c-ab43-0bc3dbd4d524.png)

**Comment by luv2001** [comment]
I would like to work on this 
Assign me
